//TODO CLASS BOOKSHELF WITH FAVORITE BOOKS AND ADDFAVORITEBOOK/PRINTFAVORITEBOOKS METHODS

//TODO LOADBOOKS FUNCTION THAT CALL FAKE REQUEST WITH CALLBACK PARAMETERS

//VAR BOOKAPI

//FAKE REQUEST FUNCTION WITH URL AND CALLBACK PARAMETER